### PR TITLE
[MEN-4717] Fix deviceconnect message drops due to slow NATS consumer

### PR DESCRIPTION
**Pull request by alfrunes**
This is far from an optimal solution but adds 'exactly once delivery' (until a
message is dropped) by requiring ACK for every message transmitted over
NATS. If an empty ack message is not returned the session will close.
This will significantly decrease the bandwith and increase latency as
the websocket connection will be throttled while waiting for ACK
messages over NATS.

### CODE REVIEW

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline

**Comment by alfrunes** [comment]
I tested the PR running the backend in the US (Iowa) and the device in Norway (Oslo) and got varying results in terms of performance. With `scp` over `port-forwarding` I got terrible results, with an average transfer speed of `~12KiB/s` for a big (10MiB) file. Also, a pure `ssh` session had over twice the amount of latency compared with the plain remote terminal protocol - which is still pretty usable.
On the other hand, normal file transfer using the deviceconnect download API end-point averaged at `365KiB/s`, which I'd also say is pretty acceptable considering the long round-trip distance :earth_americas:.

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline

**Review by tranchitella — APPROVED** [review]
I tested it and it is "good enough". It adds latency, but makes the message dropping disappear. Let's merge it, and we'll see if we can come up with a more advanced solution in the future.

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline

Sorry, @tranchitella I found a potential bug that I just had to patch.

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline

Another one...

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline

**Comment by alfrunes** [comment]
@tranchitella I'm not sure if this PR is worth it, however, I did find a more significant bug that is still present in master (see last commit ddc66080a35f0d1d4bc1d3ef589a8226b2c9a02b). The integration tests kept triggering this bug since the upload/download endpoints does not digest all error messages from NATS before abandoning the subscription.

**Comment by alfrunes** [comment]
> As discussed in internal backend team meeting we will drop this PR.

**Pull request closed without merging**
