### PR TITLE
MEN-4718 Flush of the session recorder moved one level up

### PR DESCRIPTION
**Pull request by merlin-northern**
We need to flush the session recording in any case ConnectServeWS exits

* see https://tracker.mender.io/browse/MEN-4718?focusedCommentId=116036&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-116036

ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline :)

**Review by alfrunes — APPROVED** [review]

**Review by alfrunes — COMMENTED** [review]
On a second thought, will this also record file-transfer and port forward sessions as well? :thinking:

**Comment by merlin-northern** [comment]
> On a second thought, will this also record file-transfer and port forward sessions as well? 🤔

it will create a buffered writer, but there will be nothing to flush, so I do not think there should be anything saved to the db. do you want me to check that?

**Comment by merlin-northern** [comment]
> > On a second thought, will this also record file-transfer and port forward sessions as well? 🤔
> 
> it will create a buffered writer, but there will be nothing to flush, so I do not think there should be anything saved to the db. do you want me to check that?

ok I have checked. file transfer does not save any records in recordings or control collections. merging.

**Pull request merged**
