### PR TITLE
ALV-182: Implement filetransfer download HEAD method

### PR DESCRIPTION
**Pull request by alfrunes**
Requires: https://github.com/mendersoftware/integration/pull/2518

### CODE REVIEW

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline --pr integration/2518

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline --pr integration/2518

**Review by kjaskiewiczz — COMMENTED** [review]
change looks OK, but test are failing quite badly

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline --pr integration/2518

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline --pr integration/2518

**Review by kjaskiewiczz — APPROVED** [review]
looks good

**Pull request merged**
